In [3]:
print("""
@Description: Leveraging weak learners via adaptive boosting
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-06-15 14:48:35
""")


@Description: Leveraging weak learners via adaptive boosting
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-06-15 14:48:35



# How adaptive boosting works

|index|$x$|$y$|weights|$\hat{y}(x\leq 3)$|correct|updated weights|
|---|---|---|---|---|---|---|
|1|1.0|1|.1|1|Yes|.072|
|2|2.0|1|.1|1|Yes|.072|
|3|3.0|1|.1|1|Yes|.072|
|4|4.0|1|.1|-1|Yes|.072|
|5|5.0|1|.1|-1|Yes|.072|
|6|6.0|1|.1|-1|Yes|.072|
|7|7.0|1|.1|-1|No|.167|
|8|8.0|1|.1|-1|No|.167|
|9|9.0|1|.1|-1|No|.167|
|10|10.0|1|.1|-1|Yes|.072|

In [4]:
import numpy as np
y = np.array([1, 1, 1, -1, -1, -1, 1, 1, 1, -1])
y_hat = np.array([1, 1, 1, -1, -1, -1, -1, -1, -1, -1])
correct = (y == y_hat)
weights = np.full(10, .1)
print(weights)

[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


In [5]:
epsilon = np.mean(~correct)
epsilon

0.3

In [6]:
alpha_j = .5 * np.log((1 - epsilon) / epsilon)
alpha_j

0.42364893019360184

In [7]:
update_if_correct = .1 * np.exp(-alpha_j * 1 * 1)

In [8]:
update_if_wrong_1 = .1 * np.exp(-alpha_j * -1 * 1)
update_if_wrong_1

0.1527525231651947

In [9]:
update_if_wrong_2 = .1 * np.exp(-alpha_j * 1 * -1)
update_if_wrong_2

0.1527525231651947

In [10]:
weights = np.where(correct == 1, update_if_correct, update_if_wrong_1)
weights

array([0.06546537, 0.06546537, 0.06546537, 0.06546537, 0.06546537,
       0.06546537, 0.15275252, 0.15275252, 0.15275252, 0.06546537])

In [11]:
y * y_hat

array([ 1,  1,  1,  1,  1,  1, -1, -1, -1,  1])

In [18]:
weights = weights * np.exp(-alpha_j * y * y_hat)
weights

array([0.06546537, 0.06546537, 0.06546537, 0.06546537, 0.06546537,
       0.06546537, 0.15275252, 0.15275252, 0.15275252, 0.06546537])

In [13]:
normalized_weights = weights / weights.sum()
normalized_weights

array([0.07142857, 0.07142857, 0.07142857, 0.07142857, 0.07142857,
       0.07142857, 0.16666667, 0.16666667, 0.16666667, 0.07142857])