In [1]:
print("""
@Description: First steps with PyTorch
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-04 09:09:25
""")


@Description: First steps with PyTorch
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-04 09:09:25



In [2]:
import torch
print(torch.__version__)

2.0.1


### Creating tensors in PyTorch

In [3]:
import numpy as np
np.set_printoptions(precision=3)

In [4]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [5]:
t_ones = torch.ones(2, 3)
t_ones.shape

torch.Size([2, 3])

In [6]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
rand_tensor = torch.rand(2, 3)
rand_tensor

tensor([[0.5993, 0.3636, 0.9854],
        [0.2058, 0.1137, 0.3830]])

### Manipulating the data type and shape of a tensor

In [9]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [12]:
t = torch.rand(3, 5)
t_tr = torch.transpose(t, 0, 1)
print(t.shape, '-->', t_tr.shape)

torch.Size([3, 5]) --> torch.Size([5, 3])


In [13]:
t = torch.zeros(30)
t_reshape = t.reshape(5, 6)
t_reshape.shape

torch.Size([5, 6])

Removing the unnecessary dimensions (dimensions that have size 1, which are not needed):

In [15]:
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, '->', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1]) -> torch.Size([1, 2, 4, 1])


### Applying mathematical operations to tensors

In [20]:
torch.manual_seed(1)
# torch.rand returns a tensor filled with random numbers 
# from a uniform distribution in the range of [0, 1).
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [22]:
t3 = torch.multiply(t1, t2)
t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

In [24]:
t4 = torch.mean(t1, axis=0)
t4

tensor([-0.1373,  0.2028])

In [26]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
t5

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])

In [27]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)
t6

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])

In [30]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
norm_t1

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])

In [34]:
np.sqrt(np.sum(np.square(t1.numpy()), axis=1))

array([0.678, 0.508, 1.116, 0.549, 0.185], dtype=float32)

### Split, stack, and concatenate tensors

In [35]:
torch.manual_seed(1)
t = torch.rand(6)
t

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])

In [37]:
t_splits = torch.chunk(t, 3)
t_splits

(tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347]), tensor([0.0293, 0.7999]))

In [38]:
[item.numpy() for item in t_splits]

[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

If the tensor size is not divisible by the chunks value, the last chunk will be smaller.

In [39]:
torch.manual_seed(1)
t = torch.rand(5)
t

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])

In [40]:
t_splits = torch.split(t, split_size_or_sections=[3,2])
t_splits

(tensor([0.7576, 0.2793, 0.4031]), tensor([0.7347, 0.0293]))

In [41]:
[item.numpy() for item in t_splits]

[array([0.758, 0.279, 0.403], dtype=float32),
 array([0.735, 0.029], dtype=float32)]

In [47]:
A = torch.ones(3)
B = torch.zeros(2)
C = torch.cat([A, B], axis=0)
C

tensor([1., 1., 1., 0., 0.])

In [48]:
A = torch.ones(3)
B = torch.zeros(3)
S = torch.stack([A, B], axis=0)
S

tensor([[1., 1., 1.],
        [0., 0., 0.]])

In [49]:
S = torch.stack([A, B], axis=1)
S

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])