In [1]:
print("""
@Description: First steps with PyTorch
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-04 09:09:25
""")


@Description: First steps with PyTorch
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-07-04 09:09:25



In [4]:
import torch
print(torch.__version__)

2.0.1


### Creating tensors in PyTorch

In [5]:
import numpy as np
np.set_printoptions(precision=3)

In [7]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [8]:
t_ones = torch.ones(2, 3)
t_ones.shape

torch.Size([2, 3])

In [9]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
